<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="18226" started-at="2019-03-07T02:50:02Z" finished-at="2019-03-07T02:50:21Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="18226" started-at="2019-03-07T02:50:02Z" finished-at="2019-03-07T02:50:21Z">
      <class name="MyScripts.authenticationPackage.AuthenticationTest">
        <test-method status="FAIL" signature="loginWithEmailTest()[pri:0, instance:MyScripts.authenticationPackage.AuthenticationTest@b7dd107]" name="loginWithEmailTest" duration-ms="18194" started-at="2019-03-07T02:50:02Z" finished-at="2019-03-07T02:50:21Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Master User] but found [Organizations]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Master User] but found [Organizations]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at keywords.Keywords.verifyText(Keywords.java:70)
at MyScripts.authenticationPackage.AuthenticationTest.loginWithEmailTest(AuthenticationTest.java:179)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithEmailTest -->
      </class> <!-- MyScripts.authenticationPackage.AuthenticationTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
